services:
  postgres:
    image: postgres:14
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/10-create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/20-fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      cs-network:
        ipv4_address: 172.28.1.2

networks:
  cs-network:
    ipam:
      driver: bridge
      config:
        - subnet: 172.28.0.0/16