name: macOS CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-tests:
    runs-on: macos-latest
    name: Tests for macOS
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3

      - name: Caching cargo deps
        id: ci-cache
        uses: Swatinem/rust-cache@v2

      - name: Running tests for macOS targets
        run: |
          cargo test --all-features --workspace